### ISSUE TITLE
Don't work events on calendar

### ISSUE THREAD

**Issue by anna-apanasik** [Innqube/angular-calendar-week-hours-view#10]
I want to use angular-calendar and angular-calendar-week-hours-view in my ionic application.
I installed all needed packages(angular-calendar, angular-calendar-week-hours-view, @angular/animations). I tried different versions of  angular-calendar-week-hours-view, but it didn't help. 

My current versions:
"@angular/animations": "^5.2.9",
"angular-calendar": "^0.25.2",
"angular-calendar-week-hours-view": "^1.0.1",

I got this error in console:
CalendarWeekHoursDayViewComponent.html:12 ERROR TypeError: Object(...) is not a function
    at DraggableDirective.ngOnInit (angular-draggable-droppable.js:152)
    at checkAndUpdateDirectiveInline (core.js:12369)
    at checkAndUpdateNodeInline (core.js:13893)
    at checkAndUpdateNode (core.js:13836)
    at debugCheckAndUpdateNode (core.js:14729)
    at debugCheckDirectivesFn (core.js:14670)
    at Object.eval [as updateDirectives] (CalendarWeekHoursDayViewComponent.html:12)
    at Object.debugUpdateDirectives [as updateDirectives] (core.js:14655)
    at checkAndUpdateView (core.js:13802)
    at callViewAction (core.js:14153)

This error appears when I will add events.

schedule.html (part of the file):
<iq-calendar-week-hours-view
            [viewDate]="viewDate"
            [events]="events"
            [hourSegments]="1"
            [dayStartHour]="6"
            [dayEndHour]="22"
            [weekStartsOn]="1"
            [refresh]="refresh"
            [locale]="locale">
    </iq-calendar-week-hours-view>
schedule.ts (part of the file):
 protected events: CalendarEvent[] = [
        {
            start: addHours(startOfDay(new Date()), 7),
            end: addHours(startOfDay(new Date()), 9),
            title: 'First Event',
            cssClass: 'custom-event',
            color: {
                primary: '#488aff',
                secondary: '#bbd0f5'
            },
            resizable: {
                beforeStart: true,
                afterEnd: true
            },
            draggable: true
        },
        {
            start: addHours(startOfDay(new Date()), 10),
            end: addHours(startOfDay(new Date()), 12),
            title: 'Second Event',
            cssClass: 'custom-event',
            color: {
                primary: '#488aff',
                secondary: '#bbd0f5'
            },
            resizable: {
                beforeStart: true,
                afterEnd: true
            },
            draggable: true
        }
    ];
How I can resolve this problem?

**Comment by danielptm** [comment]
@anyablischik I have the same error, why did you close? Did you solve it? If so how?

**Comment by anna-apanasik** [comment]
@danielptm yes, I decided this problem. I reinstalled version of angular-calendar.
My version: "angular-calendar": "^0.24.0", "angular-calendar-week-hours-view": "^1.0.0",
